In [9]:
import pandas as pd

In [11]:
data=pd.read_csv("C:/Users/Saptak/Desktop/Thesis_doc/Insta_paper+dataset/user_fake_authentic_2class.csv")

In [13]:
display(data.head())

,pos,flw,flg,bl,pic,lin,cl,cz,ni,erl,erc,lt,hc,pr,fo,cs,pi,class
0,44,48,325,33,1,0,12,0.0,0.0,0.00,0.00,0.000,0.0,0.0,0.000,0.111111,0.094985,f
1,10,66,321,150,1,0,213,0.0,1.0,14.39,1.97,0.000,1.5,0.0,0.000,0.206826,230.412857,f
2,33,970,308,101,1,1,436,0.0,1.0,10.10,0.30,0.000,2.5,0.0,0.056,0.572174,43.569939,f
3,70,86,360,14,1,0,0,1.0,0.0,0.78,0.06,0.000,0.0,0.0,0.000,1.000000,5.859799,f
4,3,21,285,73,1,0,93,0.0,0.0,14.29,0.00,0.667,0.0,0.0,0.000,0.300494,0.126019,f

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
X = data[['pos', 'flw', 'flg','bl','pic','lin','cl','cz','ni','erl','erc','lt','hc','pr','fo','cs','pi']]  # Features
y = data['class']

In [29]:
#random_state=42 ensures that every time you run the code, the split will be the same. This helps maintain consistency in the results when you share the code with others or rerun it multiple times.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [53]:
#Random forest apply( n_estimators - no of trees)

clf = RandomForestClassifier(n_estimators=120, random_state=42)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.4f}%")
print("Classification Report:")
print(report)

Accuracy: 89.5971%
Classification Report:
              precision    recall  f1-score   support

           f       0.95      0.84      0.89      8217
           r       0.85      0.96      0.90      8115

    accuracy                           0.90     16332
   macro avg       0.90      0.90      0.90     16332
weighted avg       0.90      0.90      0.90     16332